version: '3.9'

services:
  stash:
    build: ./app
    ports:
      - "15235:3000"
    environment:
      ENV: 'production'
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "jbnDwnCYhTvZQBh89hn"
      ADMIN_BIO: "SELEKDA{testing}"

  xssbot:
    image: siahaan/xsspawn
    # shm_size: '1gb' # Uncomment if shared memory size needs to be set
    environment:
      APP_URL: "http://159.223.58.50:15235/"
      APP_USERNAME: "admin"
      APP_PASSWORD: "jbnDwnCYhTvZQBh89hn"
      BOT_PORT: "5000"
    volumes:
      - ./scenario.js:/home/bot/scenario.js
    ports:
      - 9129:5000
    restart: always