services:
  repoweb:
    build: 
      context: ./src/repo
      args:
        FLAG: SELEKDA{hpp_and_paraMeter_inj3ct1on_yeah}
  mainweb:
    build: ./src/web
    environment:
      - REPO_APP_URL=http://repoweb:8080
      - SECRET_KEY=JustAbunhcOakasmdsqjdsjkls
    depends_on:
    - repoweb
  nginx:
    image: nginx:stable-alpine
    ports:
    - "15922:8080"
    volumes:
    - ./src/frontend/index.html:/var/www/html/index.html
    - ./src/frontend/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - mainweb
